name: Continuous Deployment (Prod)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: 100xdevs/1ai-server:${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: 100xdevs/1ai-frontend:${{ github.sha }}

      - name: Clone production-ops repo, update, and push
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://${PAT}@github.com/codes30/production-ops.git
          cd production-ops
          sed -i 's|image: 100xdevs/1ai-server:.*|image: 100xdevs/1ai-server:${{ github.sha }}|' prod/1ai/server.yml
          sed -i 's|image: 100xdevs/1ai-frontend:.*|image: 100xdevs/1ai-frontend:${{ github.sha }}|' prod/1ai/frontend.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add prod/1ai/server.yml prod/1ai/frontend.yml
          git commit -m "Update 1ai image to ${{ github.sha }}"
          git push https://${PAT}@github.com/codes30/production-ops.git main
