name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  # This job runs the linters
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "bun"

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Lint backend
        working-directory: ./backend
        run: bun run lint

      - name: Lint frontend
        working-directory: ./frontend
        run: bun run lint
